services:
  zookeeper:
    image: 'bitnami/zookeeper:3.8.2'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'  # Cho phép đăng nhập ẩn danh


  kafka:
      image: 'bitnami/kafka:3.7.0'
      container_name: kafka
      hostname: kafka
      ports:
        - '9094:9094'
      environment:
        KAFKA_BROKER_ID: 1  # ID của broker Kafka
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Địa chỉ kết nối Zookeeper
        ALLOW_PLAINTEXT_LISTENER: 'yes'  # Cho phép Kafka sử dụng giao thức không mã hóa
        KAFKA_CFG_LISTENERS: PLAINTEXT://:9094  # Cấu hình listener
        KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094  # Listener được quảng cáo để các client có thể kết nối
        KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'  # Tự động tạo topic


  mysql:
    container_name: transaction
    image: mysql:8.0.40-debian
    environment:
      MYSQL_ROOT_PASSWORD: Hanoi_1234  # Root password
      MYSQL_DATABASE: transactions_service  # Database name
      MYSQL_USER: root  # Username
      MYSQL_PASSWORD: Hanoi_1234  # Password for the user
    volumes:
      - transactions-service-db-data:/var/lib/mysql  # Volume for persistent data
    ports:
      - 3306:3306  # Expose port 3306 for MySQL

volumes:
    transactions-service-db-data:  # Volume for MySQL
